### ISSUE TITLE
Feedback Exposé

### ISSUE THREAD

**Issue by Alessa-v-Scheidt** [lisafuhrmann/EPWS2324-FuhrmannMehlemVonScheidt#3]
Hallo Zusammen,

wir hätten gerne Feedback zu unserem Exposé, dass wir in der [README.md](https://github.com/lisafuhrmann/EPWS2324-FuhrmannMehlemVonScheidt) abgelegt haben.
Sind alle essentiellen Punkte vorhanden oder gibt es Anpassungsbedarf?

**Comment by vschaefer** [comment]
Hello,
aus meiner Sicht ist alles Essentielles enthalten. Es gibt allerdings noch ein paar Punkte die ihr verbessern könnt.
Beim Problemraum beschreibt ihr zum Teil schon Anforderungen an das System.
Diese leitet man jedoch erst später aus der Problemanalyse und den Erfordernissen ab.
Zudem empfehle ich euch aus einer möglichst neutralen Perspektive zu schreiben. Also „Wir” oder „Ich” möglichst vermeiden. Im Fazit könnt ihr die Erzählperspektive mal wechseln, da die persönliche Meinung dort mit einfließt. Ansonsten solltet ihr immer neutral bleiben. Das wird besonders später im Praixsprojekt oder der Bachelorarbeit relevant. 
Was mir noch auffällt ist, dass ihr sehr oft davon schreibt, dass die Anwendung benutzerfreundlich gestaltet sein soll und ihr dies auch überprüfen wollt. Hieraus liest sich, dass der Fokus darauf liegt eine möglichst gebrauchstaugliche Benutzerschnittstelle zu entwickeln. Das würde aber eher zur Perspektive „Mensch Computer Interaktion” gehören.
